### ISSUE TITLE
Snap Package Issue - 'tb: command not found'

### ISSUE THREAD

**Issue by russarmst** [klaussinani/taskbook#114]
I installed the snap package on Mate 18.04 (sudo snap install taskbook) which completed sucessfully. I can sucessfully use the taskbook command but when I use tb i get 'tb: command not found'. Perhaps an alias is missing from the snap package?

Thanks,
Russell.

**Comment by doc-E-brown** [comment]
I have this issue as well running Kubuntu 18.04 and taskbook version 0.2.0.  The command taskbook --help, taskbook -t .... etc works correctly.  As @russarmst stated, it is probably a missing alias.

**Comment by justaboredkid** [comment]
Did you run the command `snap alias taskbook tb` as instructed on README.md?

**Comment by klaussinani** [comment]
Try setting the alias after having installed the snap:

```
snap alias taskbook tb
```
