### ISSUE TITLE
Move behaves as copy 

### ISSUE THREAD

**Issue by ksuhiyp** [klaussinani/taskbook#115]
**Describe the bug**
Moving tasks from board to anothor creates duplicates by keeping source after move operation   
**To Reproduce**
taskbook --task @board1 quick easy task 
taskbook --move  @1 board1 board1

**Expected behavior**
Should behave as move not copy by deleting source task
**Screenshots**
![screenshot from 2018-11-27 16-47-47](https://user-images.githubusercontent.com/4389890/49089432-38e54100-f264-11e8-85cc-8f318a53ff91.png)

**Technical Info (please complete the following information)**
 - OS:Cosmic cuttlefish 
 - Node.js Version:snap on Cosmic cuttlefish
 - Taskbook Version:  0.2.0

**Additional context**

**Comment by klaussinani** [comment]
Items can be moved to an existing/new board by just defining the destination board, thus there is not need to type the source one, ie:

``` bash
$ taskbook --move @5 knowledge # move item with id `5` to board `knowledge`
```
