### ISSUE TITLE
Cannot use parentheses during task creation

### ISSUE THREAD

**Issue by DLvalentine** [klaussinani/taskbook#118]
**Describe the bug**
When using parentheses in the body of a task (ex. `Do the thing (today, tomorrow maybe)`), a node error is logged. Sometimes the task is added, but most times it is not added.

**To Reproduce**
`tb -t @boardName Do some things today (maybe with the dog!)`

**Expected behavior**
Task to be created without error

**Technical Info (please complete the following information)**
 - OS: Windows 10
 - Node.js Version: Latest
 - Taskbook Version: Latest

**Comment by klaussinani** [comment]
You could either try escaping the parentheses:

```bash
tb -t @boardName Do some things today \(maybe with the dog!\)
```
or try wrapping the message with single quotes:

```bash
tb -t @boardName "Do some things today (maybe with the dog!)"
```

Please feel free to reach out if the issue persists.
