### ISSUE TITLE
How to make taskbook looks like the sceenshot?

### ISSUE THREAD

**Issue by stephane-archer** [klaussinani/taskbook#125]
In my terminal in does't look as pretty as the your screenshot.
How to modify my terminal to get the same elegant output?
[https://github.com/klaussinani/taskbook/blob/master/media/header-boards.png](https://github.com/klaussinani/taskbook/blob/master/media/header-boards.png)

**Comment by novdddd** [comment]
I think @klaussinani said it here https://github.com/klaussinani/taskbook/issues/32#issuecomment-410490297
