### ISSUE TITLE
Backup

### ISSUE THREAD

**Issue by ricardofrantz** [klaussinani/taskbook#186]
Hello,

not sure if this is the right place to post this question, but here it is...

I am using popos and installed tasbook via snap. How can I back up the data to my dropbox or google drive? I can't find the data files. Is there a function for backup - export - restore?

Thanks in advance,

**Comment by crckhd** [comment]
Hi!
You can move folder with your tasks to dropbox or google drive. Simply just copy `~/.taskbook/` (if you didn't change your config) to cloud storage. That's all😊

![image](https://user-images.githubusercontent.com/101672047/164112886-d857b1d8-6da0-4c69-b505-03b0444b22d4.png)

Here you can see folder and json file. JSON - file with your config, folder - directory with your tasks

**Comment by crckhd** [comment]
For snap you can view `~/snap/taskbook/`. There is many folders like `23, current, common` etc. Find your folder and copy it too!

![image](https://user-images.githubusercontent.com/101672047/164113750-7991d3ed-63e3-4e49-9a7f-855d1b6963c3.png)

I hope it solves your problem)

**Comment by crckhd** [comment]
@klaussinani you can close this issue😊

**Comment by klaussinani** [comment]
@ricardofrantz Thank you for taking the time to ask this question, I think you raised a good point there!

Thank you for taking the time to answer @crackidocky! 🙏
