### ISSUE TITLE
Rename boards

### ISSUE THREAD

**Issue by RyanRoberts** [klaussinani/taskbook#66]
**Is your feature request related to a problem? Please describe.**
Can't rename boards once created or no clear way to do it.

**Describe the solution you'd like**
Something like: `$ tb -e MyTasks Todos` could rename a MyTasks board to Todos…

**Comment by JordanAdams** [comment]
I almost feel like this could expand to updating task descriptions too. If that were the case, we could use of the `@` syntax for distinguishing between board and task updates:

**Rename a board**
`$ tb -e @cooking baking`

**Update a task**
`$ tb -e 1 Do something else`

**Comment by PavloCherniovyi** [comment]
Made a [PR](https://github.com/klauscfhq/taskbook/pull/73).
